-- CREATE DATABASE IF NOT EXISTS twitter;

-- CREATE TABLE user (
--   id int NOT NULL AUTO_INCREMENT,
--   user_handle varchar(64) NOT NULL UNIQUE,
--   display_name varchar(128) DEFAULT NULL,
--   email varchar(64) NOT NULL UNIQUE,
--   background_pic varchar(128) DEFAULT NULL,
--   profile_pic varchar(128) DEFAULT NULL,
--   created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- create table tweet (
--   id bigint NOT NULL AUTO_INCREMENT, 
--   user_id int NOT NULL, 
--   message varchar(150), 
--   ip_address varchar(40),
--   likes int DEFAULT 0,
--   is_delete tinyint DEFAULT 0,
--   created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, 
--   updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
--   PRIMARY KEY(id), 
--   KEY (user_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 23:30:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twitter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `twitter` ;

-- -----------------------------------------------------
-- Schema twitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter` DEFAULT CHARACTER SET utf8mb4 ;
USE `twitter` ;

-- -----------------------------------------------------
-- Table `twitter`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter`.`user` ;

CREATE TABLE IF NOT EXISTS `twitter`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_handle` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(128) NULL,
  `email` VARCHAR(64) NOT NULL,
  `background_pic` VARCHAR(128) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_handle_UNIQUE` (`user_handle` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter`.`tweet` ;

CREATE TABLE IF NOT EXISTS `twitter`.`tweet` (
  `id` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `message` VARCHAR(150) NULL,
  `ip_address` VARCHAR(40) NULL,
  `likes` INT NULL DEFAULT 0,
  `id_delete` TINYINT(0) NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter`.`likes` ;

CREATE TABLE IF NOT EXISTS `twitter`.`likes` (
  `id` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tweet_id` BIGINT(0) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_user_tweet` (`user_id` ASC, `tweet_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter`.`follow` ;

CREATE TABLE IF NOT EXISTS `twitter`.`follow` (
  `id` INT NOT NULL,
  `follower_id` INT NOT NULL,
  `followee_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_follow` (`follower_id` ASC, `followee_id` ASC) VISIBLE,
  INDEX `idx_followee` (`followee_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter`.`comment` ;

CREATE TABLE IF NOT EXISTS `twitter`.`comment` (
  `id` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `tweet_id` BIGINT(0) NOT NULL,
  `user_id` INT NOT NULL,
  `comment` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_tweet` (`tweet_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
